### PR TITLE
Update node modules

### PR DESCRIPTION
**Pull request by kdorosh**
updates node modules per `npm install` to ensure the changes in https://github.com/arduino/setup-protoc/pull/12 are properly picked up to actually resolve https://github.com/arduino/setup-protoc/issues/13

Fix came from our fork that is working for us. Please wait to merge until I confirm this works

### CODE REVIEW

**Comment by kdorosh** [comment]
passes all tests with `npm run test`

**Comment by kdorosh** [comment]
Tested in our ci flow, works and resolves https://github.com/arduino/setup-protoc/issues/13

The our ci flow tested in https://github.com/solo-io/gloo/pull/3874 , the successful run: https://github.com/solo-io/gloo/pull/3874/checks?check_run_id=1408007411

**Comment by rsora** [comment]
@kdorosh thanks!
wow it seems that a lot of stuff is added to the `node_modules` folder, are you sure that this is all necessary?
I'm not super expert with TS, but it seems that when pulling your PR a very big amount of stuff is downloaded, maybe also dev-dependencies were downloaded during your update?
```
$ gh pr checkout 17  
remote: Enumerating objects: 2122, done.
remote: Counting objects: 100% (2122/2122), done.
remote: Compressing objects: 100% (1806/1806), done.
remote: Total 7692 (delta 309), reused 1997 (delta 253), pack-reused 5570
Receiving objects: 100% (7692/7692), 19.16 MiB | 4.94 MiB/s, done.
Resolving deltas: 100% (1308/1308), completed with 14 local objects.
From github.com:arduino/setup-protoc
 * [new ref]         refs/pull/17/head -> update_with_upstream
Switched to branch 'update_with_upstream'
```

**Comment by kdorosh** [comment]
I just ran `npm install`, it does seem like a lot. Perhaps I did snag dev dependencies as well. Not sure all of it is necessary.

**Comment by rsora** [comment]
I see @kdorosh, may I ask you to test again in your CI the current `master` branch? 

I did an upgrade and a bit of dev dependencies cleanups.

In the meantime, I'm setting up a test env, but maybe you are quicker than me, I lost a bit of my grip on Github Actions :smile_cat:

**Comment by kdorosh** [comment]
current arduino master works with our ci, tested in https://github.com/solo-io/gloo/pull/3875 (the passing check https://github.com/solo-io/gloo/pull/3875/checks?check_run_id=1408161055)

closing this PR since https://github.com/arduino/setup-protoc/pull/16 handles it more cleanly

thanks @rsora !

**Comment by rsora** [comment]
Thanks @kdorosh for your support, this nice interaction reminded me why I signed to be an OSS maintainer for Arduino :+1: 

I'm preparing a tag and a release for the Action in the next minutes, keep your eyes peeled :smile_cat:

**Pull request closed without merging**
