### PR TITLE
Support only the new protobuf versioning scheme

### PR DESCRIPTION
**Pull request by alessio-perugini**
Support for new protobuf tag naming `vMINOR.PATCH`.
This require a bump to `v2`

After [v3.20.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0) the pre-compiled binaries are pushed only for minor.patch tags.
Looking at the [docs](https://protobuf.dev/support/version-support/) I think the best way to handle this is to bump a new major of our GA and start supporting only the minor.patch tags. This would make our life easier (at least until protobuf team doesn't want to change the tag strategy again :rofl: )

### CODE REVIEW

**Review by MatteoPologruto — APPROVED** [review]
LGTM

**Comment by jbohanon** [comment]
Were tags deleted as a part of this effort? Our team had a dependency on `3.6.1` and we are now broken. Is there documentation on if/how the old tags are mapped to existing tags?

**Comment by alessio-perugini** [comment]
@jbohanon do you mind pasting how you pinned the action? Something Like:
```
        uses: arduino/setup-protoc@v1
        with:
          version: v3.16.0
```
We didn't touch any older tags :thinking:

**Comment by jbohanon** [comment]
Thanks for the prompt response! We had:
```
Run arduino/setup-protoc@master
  with:
    version: 3.6.1
    repo-token: ***
    include-pre-releases: false
Error: Error: unable to get latest version
```

We are now testing the following with success. Looks like there was smoke but no fire. :smile:  Thanks again
```
Run arduino/setup-protoc@v1
```

**Comment by alessio-perugini** [comment]
@jbohanon Yup that's because the https://github.com/arduino/setup-protoc/commit/28fd3e5ddcc4ae8820e0c2085bfea8ab68f631e3 will be released ~tomorrow as a v2 breaking change.

Honestly, I didn't think about the users referencing the action with `@master` Sorry about that :pray: 
Glad that you solved it by pinning at `@v1` :smile:

**Comment by jbohanon** [comment]
It's all good, I see now that your documentation has called out for _quite some time_ that users should reference `@v1`. All sorted!

**Pull request merged**
